version: '2.4'

services:

  client:
    build:
      context: ./client
      target: production
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - file_uploads:/usr/share/nginx/html/public/images
    networks:
      - frontend
    ports:
      - 3000:80

  server:
    build:
      context: ./server
      target: development
    environment:
      PORT: 5000
      DATABASE_URL: mysql://prisma:prisma@db/prisma
      JWT_SECRET: myverysecretsecret
      JWT_EXPIRES_IN: 1h
    volumes:
      - ./server/:/app
      - /app/node_modules
      - file_uploads:/app/public/images
    networks:
      - frontend
      - backend
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.8
    environment:
      MARIADB_ROOT_PASSWORD: prisma
      MARIADB_DATABASE: prisma
      MARIADB_PASSWORD: prisma
      MARIADB_USER: prisma
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: '/usr/bin/mysql -uprisma -pprisma -e "SHOW DATABASES;"'
      timeout: 5s
      interval: 5s
      retries: 5

volumes:
  db_data: {}
  file_uploads: {}

networks:
  frontend: {}
  backend: {}
